# Generated by Django 4.2.17 on 2025-02-13 15:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('checkbox_newsletter', models.BooleanField(default=False)),
                ('symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('symptom_text', models.TextField(blank=True, null=True)),
                ('symptom_severity', models.IntegerField(blank=True, null=True)),
                ('symptom_duration', models.CharField(max_length=200)),
                ('was_already_treated', models.BooleanField()),
                ('previous_treatment_person', models.TextField(blank=True, null=True)),
                ('previously_taken_medication', models.BooleanField()),
                ('previous_medication_details', models.TextField(blank=True, null=True)),
                ('previously_taken_cannabis', models.BooleanField()),
                ('previous_cannabis_details', models.TextField(blank=True, null=True)),
                ('medication_wish', models.JSONField()),
                ('checkbox_honesty', models.BooleanField()),
                ('checkbox_data_sharing', models.BooleanField()),
                ('checkbox_data_policy', models.BooleanField()),
                ('agreed_no_exclusion_criteria', models.BooleanField()),
                ('doctor_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
