# Generated by Django 4.2.17 on 2025-02-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationrequest',
            name='checkbox_data_policy',
        ),
        migrations.RemoveField(
            model_name='medicationrequest',
            name='checkbox_data_sharing',
        ),
        migrations.RemoveField(
            model_name='medicationrequest',
            name='checkbox_honesty',
        ),
        migrations.RemoveField(
            model_name='medicationrequest',
            name='checkbox_newsletter',
        ),
        migrations.CreateModel(
            name='MedicationRequestOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
