# Generated by Django 4.2.17 on 2025-02-13 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiry', '0003_remove_product_updated_medicationrequest_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationrequest',
            options={'ordering': ('created',)},
        ),
        migrations.CreateModel(
            name='MedicationRequestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_request_answers', to=settings.AUTH_USER_MODEL)),
                ('medication_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='inquiry.medicationrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
