# Generated by Django 4.2.17 on 2025-02-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_alter_medicationrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationrequest',
            name='previous_treatment_person',
        ),
    ]
