# Generated by Django 4.2.17 on 2025-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_remove_medicationrequest_previous_treatment_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestanswer',
            name='diagnosis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestanswer',
            name='medication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestanswer',
            name='private_notes',
            field=models.TextField(null=True),
        ),
    ]
