# Generated by Django 4.2.17 on 2025-02-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_medicationrequestanswer_diagnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationRequestAnswer',
        ),
    ]
