databases:
  - name: tascardodb
    plan: free
    databaseName: tascardo
    user: tascardouser

services:
  - type: web
    plan: free
    name: tascardo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn medicanova.asgi:application -k medicanova.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tascardodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4