# Generated by Django 4.2.17 on 2025-02-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestanswer',
            name='was_processed',
            field=models.BooleanField(default=False),
        ),
    ]
