# Generated by Django 4.2.17 on 2025-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_medicationrequestanswer_was_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequestanswer',
            name='was_approved',
            field=models.BooleanField(null=True),
        ),
    ]
