# Generated by Django 4.2.17 on 2025-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkbox_data_policy',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_data_sharing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_honesty',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
