# Generated by Django 4.2.17 on 2025-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_checkbox_data_policy_user_checkbox_data_sharing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10),
        ),
    ]
