# Generated by Django 4.2.17 on 2025-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checkbox_honesty',
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_communication',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_costs',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='checkbox_withdrawal',
            field=models.BooleanField(null=True),
        ),
    ]
