# Generated by Django 4.2.17 on 2025-02-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_checkbox_honesty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checkbox_costs',
        ),
    ]
